permissions:
  contents: read
  issues: write
  pull-requests: write
  packages: read
  deployments: write
  repository-projects: write

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'


name: Production
jobs:
  manage-project:
    runs-on: ubuntu-latest
    steps:
      - name: Create a new project card
        uses: actions/github-script@v4
        with:
          script: |
            const issue = await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'New Issue from GitHub Actions',
              body: 'This issue was automatically created by a GitHub Action.',
              labels: ['bug']
            });
            console.log(`Created issue: ${issue.data.html_url}`);
