permissions:
  contents: read
  issues: write
  pull-requests: write
  packages: read
  deployments: write
  repository-projects: write

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'

name: Production
jobs:
  manage-project:
    runs-on: ubuntu-latest
    steps:
      - name: Create a new project card
        uses: actions/github-script@v4
        with:
          script: |
            const projectUrl = 'https://api.github.com/repos/${{ github.repository }}/projects';
            const response = await github.request('POST ' + projectUrl, {
              name: 'New Project',
              body: 'This is a new project created by GitHub Actions',
              headers: {
                accept: 'application/vnd.github.inertia-preview+json'
              }
            });
            console.log(response.data);
